### ISSUE TITLE
Datapack in aternos

### ISSUE THREAD

**Issue by LukeisTheBESTT** [Seeloewen/Random-Item-Giver-Datapack#34]
I tried putting the 1.5.0. zip file in aternos by datapacks but when i launched the server i diddnt see any commands or things like that. (im quite new to launching and doing datapacks so excuse me if i sound dumb). Is there like a command for the datapack or did i put the wrong file my server is on 1.21

**Comment by Seeloewen** [comment]
Can you tell me if you see a message that confirms that the Random Item Giver was loaded when executing **/reload**?
It should look somewhat like this: 
![reload_message_1_3_0](https://github.com/user-attachments/assets/0c9875d1-1822-4069-a700-c0215d75ae78)

Otherwise, make sure that the datapack is installed correctly. It should be in the 'datapacks' folder of your server's world. Since you're using 1.5.0, the file should be called exactly "random-item-giver-1-5-0-mc-1-21.zip". Can you show me a screenshot of your datapacks folder?

**Comment by LukeisTheBESTT** [comment]
the file is named random-item-giver-1.5.0.zip and
![Schermafbeelding 2024-10-26 165043](https://github.com/user-attachments/assets/f391ed63-07a8-4e63-acb3-fb18730c7de7)

**Comment by Seeloewen** [comment]
The datapack is in the right place, though the name doesn't fit. Can you redownload the datapack from this GitHub releases page? Make sure to select version 1.5.0 if you need it for 1.21.0, as I've released 1.5.1 for 1.21.3 yesterday.

**Comment by Seeloewen** [comment]
I will marked this issue as completed due to inactivity. If another issue arises, let me know.
